### ISSUE TITLE
Legyen icon?

### ISSUE THREAD

**Issue by Zal-n** [Zal-n/Zal-n.github.io#3]

**Comment by Zal-n** [comment]
Egyszerű egyébként

**Comment by sbalaza222** [comment]
meg tudod csinálni?

**Comment by Zal-n** [comment]
Feltöltöd utána <link type="icon">

**Comment by sbalaza222** [comment]
ha kuldesz egy képet

**Comment by sbalaza222** [comment]
persze én csak html szinten tudom megcsinálni. ha a domain-nél kell beállítani, akkor nem tudom.

**Comment by Zal-n** [comment]
Böngészőben van
